title: Rossmoyne Senior High School github page
description: This page is made by students from the robotics club and DOES NOT represent any actual real announcements
remote_theme: rshs-robotics-club/just-the-docs
# previews and searches
search_enabled: true
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10
search.tokenizer_separator: /[\s/]+/
search.rel_url: false
search.button: true

aux_links:
  "the code on github":
    - "//github.com/rm-robotics/ev3dev-cpp-template-wrapper"

defaults:
  -
    scope:
      path: "docs/" # an empty string here means all files in the project
    values:
      layout: default
  # -
  #   scope:
  #     path: "docs/ev3wrap"
  #   values:
  #     parent: ev3wrapDocPage

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one